FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY alembic.ini .
COPY alembic ./alembic
COPY tests ./tests
COPY pytest.ini .

EXPOSE 8000

CMD python -m app.db_migrate && uvicorn app.main:app --host 0.0.0.0 --port 8000
