"""Proves alembic/env.py's render_as_batch=True is effective on SQLite.

Autogenerates a real revision (into a tmp versions dir, never the committed
one) for a column that exists in the DB but not in the models, asserts the
generated code uses ``batch_alter_table`` (only emitted when env.py sets
render_as_batch=True), then runs it and checks the column is dropped and
existing rows survive.
"""

from __future__ import annotations

import os

import sqlalchemy
from alembic import command
from alembic.config import Config

from app.db_migrate import _build_config, upgrade_to_head


def _columns(engine: sqlalchemy.engine.Engine) -> list[tuple]:
    with engine.connect() as conn:
        return [tuple(r) for r in conn.execute(sqlalchemy.text("PRAGMA table_info(items)"))]


def test_autogenerated_drop_column_uses_batch_and_runs(tmp_path, monkeypatch) -> None:
    monkeypatch.delenv("DATA_DIR", raising=False)
    url = f"sqlite:///{tmp_path / 'batch.db'}"
    upgrade_to_head(url)

    engine = sqlalchemy.create_engine(url)
    head_columns = _columns(engine)
    with engine.begin() as conn:
        conn.execute(sqlalchemy.text("ALTER TABLE items ADD COLUMN zz_extra TEXT"))
    names = [c[1] for c in _columns(engine)]
    assert "zz_extra" in names

    with engine.begin() as conn:
        # Insert a row satisfying NOT NULL columns without defaults.
        values = {}
        for c in head_columns:
            if c[3] == 1 and c[4] is None:
                if c[5]:
                    continue
                t = (c[2] or "").upper()
                values[c[1]] = 0 if any(k in t for k in ("INT", "FLOAT", "NUMERIC", "REAL", "BOOL")) else "x"
        values["zz_extra"] = "gone"
        cols = ", ".join(values)
        params = ", ".join(f":{k}" for k in values)
        conn.execute(sqlalchemy.text(f"INSERT INTO items ({cols}) VALUES ({params})"), values)
        count_before = conn.execute(sqlalchemy.text("SELECT COUNT(*) FROM items")).scalar()
    assert count_before == 1

    # Autogenerate into a tmp versions dir; keep committed dir in the chain.
    config: Config = _build_config(url)
    committed = config.get_main_option("script_location") + "/versions"
    versions_tmp = tmp_path / "versions"
    versions_tmp.mkdir()
    config.set_main_option("version_locations", os.pathsep.join([committed, str(versions_tmp)]))
    config.set_main_option("version_path_separator", "os")
    rev = command.revision(
        config, message="drop zz_extra", autogenerate=True, version_path=str(versions_tmp)
    )
    source = open(rev.path).read()
    assert "batch_alter_table" in source
    assert "zz_extra" in source

    command.upgrade(config, "head")

    assert [c[1] for c in _columns(engine)] == [c[1] for c in head_columns]
    with engine.connect() as conn:
        assert conn.execute(sqlalchemy.text("SELECT COUNT(*) FROM items")).scalar() == 1
    engine.dispose()


def test_head_schema_unchanged_by_batch_mode(tmp_path, monkeypatch) -> None:
    """Fresh upgrade to head still yields the same schema as the models."""
    monkeypatch.delenv("DATA_DIR", raising=False)
    url = f"sqlite:///{tmp_path / 'fresh.db'}"
    upgrade_to_head(url)
    engine = sqlalchemy.create_engine(url)
    names = [c[1] for c in _columns(engine)]
    assert "user_hint" in names
    engine.dispose()
