"""baseline schema

Revision ID: 304649b20ea1
Revises: 
Create Date: 2026-08-08 17:13:08.151823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304649b20ea1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.Column('identified_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('search_keywords', sa.JSON(), nullable=True),
    sa.Column('suggested_price', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('pending', 'sell', 'give_away', 'throw_away', name='decision', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending_identification', 'pending_search', 'pending_decision', 'decided', 'listed', 'given_away', 'disposed', name='itemstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparable_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparable_listings')
    op.drop_table('items')
    # ### end Alembic commands ###
