"""add user_hint column

Revision ID: 56db6b756990
Revises: 304649b20ea1
Create Date: 2026-08-08 17:13:26.536205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56db6b756990'
down_revision: Union[str, Sequence[str], None] = '304649b20ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_hint', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'user_hint')
    # ### end Alembic commands ###
