"""add suggested_title and suggested_description columns

Revision ID: 5e5bc01d3d06
Revises: 56db6b756990
Create Date: 2026-08-08 22:57:59.304857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5bc01d3d06'
down_revision: Union[str, Sequence[str], None] = '56db6b756990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('suggested_title', sa.String(), nullable=True))
    op.add_column('items', sa.Column('suggested_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'suggested_description')
    op.drop_column('items', 'suggested_title')
    # ### end Alembic commands ###
