"""add item_photos table

Revision ID: 86771ea861cc
Revises: 85b6c1c63d41
Create Date: 2026-10-06 05:21:27.392477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86771ea861cc'
down_revision: Union[str, Sequence[str], None] = '85b6c1c63d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_photos_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###

    # Data backfill (hand-added): one cover photo row (position 0) per
    # existing item, copied from items.photo_path. NOT EXISTS keeps it
    # idempotent if an item already has photo rows.
    op.execute(
        "INSERT INTO item_photos (item_id, photo_path, position, created_at) "
        "SELECT i.id, i.photo_path, 0, i.created_at FROM items i "
        "WHERE NOT EXISTS (SELECT 1 FROM item_photos p WHERE p.item_id = i.id)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_photos_item_id'))

    op.drop_table('item_photos')
    # ### end Alembic commands ###
