"""add search_query_used column

Revision ID: c19b13a0cfc6
Revises: 5e5bc01d3d06
Create Date: 2026-08-10 06:56:48.080511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19b13a0cfc6'
down_revision: Union[str, Sequence[str], None] = '5e5bc01d3d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('search_query_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'search_query_used')
    # ### end Alembic commands ###
